### ISSUE TITLE
Different error messages for invalid indices

### ISSUE THREAD

**Issue by weiyang13** [AY1920S1-CS2103T-W12-4/main#237]
just putting this because there are so many bugs posted for this for some reason.

whether or not we recognise this as a bug is something else

**Comment by nexolute** [comment]
I don't think we should fix this bug. When the index is not positive, it is a parsing error because the user did not follow the format indicated in the UG. When the index is over the largest index, it is NOT a parsing error, so a more directed error message should be shown. This is the current behaviour, and I don't see a need to change. I recommend we close this issue.

**Comment by weiyang13** [comment]
I agree @nexolute
