### ISSUE TITLE
Missing future transactions from default repeaters

### ISSUE THREAD

**Issue by weiyang13** [AY1920S1-CS2103T-W12-4/main#255]
There should be transactions in december, which do not show up by default. I believe I may have used the wrong code when adding the sample data.

**Comment by LeeYiyuan** [comment]
You won't believe this but I had a terrible brain fart one day and forgot about zero indexing, leading to buggy outcomes for the month of December (see https://github.com/AY1920S1-CS2103T-W12-4/main/blob/4af3c08bc7373835b2477c16f4c3ad004ad9d80f/src/main/java/seedu/ichifund/model/util/SampleDataUtil.java#L144).

I've since fixed the issue and centralized the codes to deal with the associated transactions, but missed out on propagating the changes to `SampleDateUtil.java`. Will do so soon.
